<?php
/**
 * Class to manage Spectra Extensions.
 *
 * @package Spectra
 */

namespace SpectraBlocks;

use SpectraBlocks\Extensions\Animations;
use SpectraBlocks\Extensions\BlockJsCompiler;
use SpectraBlocks\Extensions\DisplayConditions;
use SpectraBlocks\Extensions\ImageMask;
use SpectraBlocks\Extensions\ResponsiveConditions;
use SpectraBlocks\Extensions\ResponsiveControls;
use SpectraBlocks\Extensions\StickyContainer;
use SpectraBlocks\Extensions\ZIndex;
use SpectraBlocks\GlobalStyles\Engine as GlobalStylesEngine;
use SpectraBlocks\StyleGuide\Engine as StyleGuideEngine;
use SpectraBlocks\Traits\Singleton;

defined( 'ABSPATH' ) || exit;

/**
 * Class to manage Spectra Extensions.
 *
 * @since 3.0.0
 */
class ExtensionManager {

	use Singleton;

	/**
	 * Initializes the extension manager by registering all extensions.
	 *
	 * @since 3.0.0
	 * @return void
	 */
	public function init() {
		$this->init_extensions();

		add_action( 'enqueue_block_editor_assets', array( $this, 'register_extensions' ) );
	}

	/**
	 * Initializes all extensions by calling their init() method.
	 *
	 * This method is used to trigger the initialization of all extensions.
	 * when the extension manager is initialized.
	 *
	 * @since 3.0.0
	 *
	 * @return void
	 */
	public function init_extensions() {
		$animations_enabled         = 'disabled' !== \Spectra_Blocks_Admin_Helper::get_admin_settings_option( 'spectra_blocks_enable_animations_extension', 'enabled' );
		$responsive_enabled         = 'disabled' !== \Spectra_Blocks_Admin_Helper::get_admin_settings_option( 'spectra_blocks_enable_block_responsive', 'enabled' );
		$display_conditions_enabled = 'disabled' !== \Spectra_Blocks_Admin_Helper::get_admin_settings_option( 'spectra_blocks_enable_display_conditions', 'enabled' );

		if ( $animations_enabled ) {
			( Animations::instance() )->init();
		}

		if ( $display_conditions_enabled ) {
			( DisplayConditions::instance() )->init();
		}

		( ImageMask::instance() )->init();

		// Render per-block `spectraCustomJS` in wp_footer. Lives in free so
		// imported/authored block JS runs without Spectra Pro.
		( BlockJsCompiler::instance() )->init();

		if ( $responsive_enabled ) {
			( ResponsiveControls::instance() )->init();
			( ResponsiveConditions::instance() )->init();
		}

		( StickyContainer::instance() )->init();
		( ZIndex::instance() )->init();
		StyleGuideEngine::init();
		GlobalStylesEngine::init();
	}

	/**
	 * Enqueues all extensions editor assets.
	 *
	 * This method scans the 'build/extensions/' directory for subdirectories containing
	 * an 'index.asset.php' file, and calls the enqueue_editor_extension_assets() method
	 * for each of them.
	 *
	 * @since 3.0.0
	 *
	 * @return void
	 */
	public function register_extensions() {
		$extensions_dir = SPECTRA_BLOCKS_DIR . 'build/extensions/';

		if ( ! is_dir( $extensions_dir ) || ! is_readable( $extensions_dir ) ) {
			return;
		}

		$extension_files = glob( $extensions_dir . '*/index.asset.php' );

		if ( empty( $extension_files ) ) {
			return;
		}

		// Process all extensions.
		foreach ( $extension_files as $extension_file ) {
			$this->enqueue_editor_extension_assets( $extension_file );
		}
	}

	/**
	 * Enqueues editor assets for a given extension.
	 *
	 * @since 3.0.0
	 *
	 * @param string $extension_file Path to the extension's asset file.
	 * @return void
	 */
	private function enqueue_editor_extension_assets( $extension_file ) {
		if ( ! file_exists( $extension_file ) ) {
			return;
		}

		$extension_dir = dirname( $extension_file );
		$folder_name   = basename( $extension_dir ); // Get extension folder name.
		$handle        = "spectra-blocks-extension-{$folder_name}-editor";
		$script_url    = SPECTRA_BLOCKS_URL . "build/extensions/{$folder_name}/index.js";
		$script_path   = SPECTRA_BLOCKS_DIR . "build/extensions/{$folder_name}/index.js";

		if ( ! file_exists( $script_path ) ) {
			return;
		}

		// Load the asset file generated by Webpack.
		$asset_file = include_once $extension_file;

		// Handle case where include_once returns true (already included).
		if ( true === $asset_file ) {
			$asset_file = array(
				'dependencies' => array(),
				'version'      => '1.0.0',
			);
		}

		// Ensure we have a valid asset file array.
		if ( ! is_array( $asset_file ) ) {
			return;
		}

		wp_enqueue_script(
			$handle,
			$script_url,
			isset( $asset_file['dependencies'] ) ? $asset_file['dependencies'] : array(),
			isset( $asset_file['version'] ) ? $asset_file['version'] : '1.0.0',
			true
		);
		wp_set_script_translations( $handle, 'spectra-blocks', SPECTRA_BLOCKS_DIR . 'languages' );

		// Enqueue extracted CSS stylesheets (if any) produced by webpack for this extension.
		$is_rtl      = is_rtl();
		$css_pattern = $is_rtl ? 'style-*-rtl.css' : 'style-*.css';
		$css_files   = glob( $extension_dir . '/' . $css_pattern );

		if ( ! empty( $css_files ) ) {
			// Filter out RTL files when not RTL (glob may match both).
			if ( ! $is_rtl ) {
				$css_files = array_filter(
					$css_files,
					function ( $file ) {
						return ! str_ends_with( $file, '-rtl.css' );
					}
				);
			}

			foreach ( $css_files as $css_file ) {
				$css_basename = basename( $css_file, '.css' );
				$css_handle   = "spectra-3-extension-{$folder_name}-{$css_basename}";
				$css_url      = SPECTRA_BLOCKS_URL . "build/extensions/{$folder_name}/" . basename( $css_file );
				// Version by the stylesheet's own mtime, not the JS asset hash —
				// otherwise CSS-only rebuilds (e.g. SCSS changes) reuse the old
				// ?ver= and browsers keep serving the stale stylesheet.
				$version = file_exists( $css_file )
					? filemtime( $css_file )
					: ( isset( $asset_file['version'] ) ? $asset_file['version'] : '1.0.0' );

				wp_enqueue_style( $css_handle, $css_url, array(), $version );
			}
		}
		// Localize script data for the image mask extension.
		if ( 'image-mask' === $folder_name ) {
			wp_localize_script(
				$handle,
				'spectraBlocksExtensions',
				array(
					'pluginUrl' => trailingslashit( SPECTRA_BLOCKS_URL ),
					'assetsUrl' => trailingslashit( SPECTRA_BLOCKS_URL ) . 'assets/',
				)
			);
		}

		/**
		 * Fires after enqueuing the editor assets for the given extension.
		 *
		 * The dynamic portion of the filter name is the extension folder name.
		 *
		 * @since 3.0.0
		 */
		do_action( 'spectra_blocks_extensions_editor_assets', $folder_name, $asset_file );
	}
}
